version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/frontend"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
