---
version: "3.8"
services:
  postgis:
    image: "postgis/postgis:12-3.1-alpine"
    restart: "unless-stopped"
    networks:
      jore:
        aliases:
          - postgis
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 30s
      start_period: 5s
      timeout: 10s
      retries: 3

  hasura:
    image: "hasura/graphql-engine:v1.3.3.cli-migrations-v2"
    depends_on:
      postgis:
        condition: "service_healthy"
    restart: "unless-stopped"
    networks:
      jore:
        aliases:
          - hasura
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET:-hasura-admin-secret-key}"
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgis:5432/postgres"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
    volumes:
      - "./hasura/migrations:/hasura-migrations"
      - "./hasura/metadata:/hasura-metadata"
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "-q", "http://localhost:8080/healthz"]
      interval: 30s
      start_period: 5s
      timeout: 10s
      retries: 3

  frontend:
    networks:
      jore:
        aliases:
          - frontend
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    depends_on:
      hasura:
        condition: "service_healthy"
    restart: "unless-stopped"
    ports:
      - "3000:80"

  proxy:
    depends_on:
      - hasura
      - frontend
    image: nginx:alpine
    volumes:
      - $PWD/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      jore:
        aliases:
          - proxy
    ports:
      - 1234:80

networks:
  jore:
    name: jore_network
