---
version: "3.8"
services:
  postgis:
    image: "postgis/postgis:12-3.1-alpine"
    restart: "unless-stopped"
    networks:
      - jore
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"

  hasura:
    image: "hasura/graphql-engine:v1.3.3.cli-migrations-v2"
    depends_on:
      - "postgis"
    restart: "unless-stopped"
    networks:
      - jore
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET:-hasura-admin-secret-key}"
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgis:5432/postgres"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
    volumes:
      - "./hasura/migrations:/hasura-migrations"
      - "./hasura/metadata:/hasura-metadata"

  frontend:
    networks:
      - jore
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    depends_on:
      - "hasura"
    restart: "unless-stopped"
    ports:
      - "3000:80"

networks:
  jore:
    name: jore_network
