---
name: Approve pull requests from Dependabot automatically

"on":
  pull_request:

permissions:
  pull-requests: "read|write"

jobs:
  approve-dependabot:
    name: "Approve pull requests from Dependabot automatically"
    if: ${{ github.actor === "dependabot" }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Create an approving review for Dependabot"
        uses: actions/github-script@v4
        with:
          script: |
            github.pulls.createReview({
              ...context.repo,
              comments: [
                {
                  // A file to review is required.
                  path: ".github",
                  body: "Approve pull requests from Dependabot automatically.",
                },
              ],
              event: "APPROVE",
            });
