name: Docker Build & Push

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build & Push docker image to dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract branch name to env variable # https://github.community/t/run-step-on-if-branch-tag-is/16965/5
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Set environment variables
        run: |
          echo "FRONTEND_IMAGE=hsldevcom/jore4-frontend" >> $GITHUB_ENV
          echo "COMMIT_ID=$BRANCH_NAME-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Pull previous image to support caching
        run: docker pull $FRONTEND_IMAGE:builder || echo "Previous builder image not found"

      - name: build dependencies & source code into builder image to support caching
        run: docker build --cache-from=$FRONTEND_IMAGE:builder --target build -t $FRONTEND_IMAGE:builder --build-arg REACT_APP_GIT_HASH=$GITHUB_SHA ./frontend

      - name: build frontend's docker image for distribution
        run: docker build --cache-from=$FRONTEND_IMAGE:builder --cache-from=$FRONTEND_IMAGE:dev -t $FRONTEND_IMAGE:dev --build-arg REACT_APP_GIT_HASH=$GITHUB_SHA ./frontend

      - name: tag frontend's docker image as 'latest'
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker tag $FRONTEND_IMAGE:dev $FRONTEND_IMAGE:latest

      - name: tag frontend's docker image as '<branch_name>-<git_commit_sha>'
        run: docker tag $FRONTEND_IMAGE:dev $FRONTEND_IMAGE:$COMMIT_ID

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.JORE4_DOCKERHUB_USER }}
          password: ${{ secrets.JORE4_DOCKERHUB_TOKEN }}

      - name: Push dev build to Docker Hub
        run: docker push $FRONTEND_IMAGE:$COMMIT_ID

      - name: Push resf of the tags to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push $FRONTEND_IMAGE:builder
          docker push $FRONTEND_IMAGE:dev
          docker push $FRONTEND_IMAGE:latest
